export const data = [
  "Q&A",
  "Grammar correction",
  "Summarize for a 2nd grader",
  "Natural language to OpenAI API",
  "Text to command",
  "Movie to Emoji",
  "Advanced tweet classifier",
  "Classification",
  "Factual answering",
  "Tweet classifier",
  "English to other languages",
  "Natural language to Stripe API",
  "SQL translate",
  "Parse unstructured data",
  "Python to natural language",
  "Calculate Time Complexity",
  "Translate programming languages",
  "Explain code",
  "Keywords",
  "Ad from product description",
  "Product name generator",
  "TL;DR summarization",
  "Python bug fixer",
  "Spreadsheet creator",
  "JavaScript helper chatbot",
  "ML/AI language model tutor.",
  "Science fiction book list maker",
  "Airport code extractor",
  "SQL request",
  "Extract contact information",
  "JavaScript to Python",
  "Friend chat",
  "Mood to color",
  "Write a Python docstring",
  "Analogy maker",
  "JavaScript one line function",
  "Micro horror story creator",
  "Third-person converter",
  "Notes to summary",
  "VR fitness idea generator",
  "Essay outline",
  "Recipe creator (eat at your own risk)",
  "Chat",
  "Marv the sarcastic chat bot",
  "Turn by turn directions",
  "Restaurant review creator",
  "Create study notes",
  "Interview questions"
];
